apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - subscription_service.yaml
images:
  - name: subscription_service
    newName: mayaralima22/subscription_service
    newTag: 221212.c9c3f5c